name: C++ CI Workflow

on:
  push:
    branches:
      - master  # или любая другая ветка, для которой ты хочешь настроить CI
  pull_request:
    branches:
      - master  # или любая другая ветка

jobs:
  build:
    runs-on: windows-latest  # Можно использовать другие ОС, например, windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up C++ Compiler
        uses: actions/setup-cpp@v1  # Эта action поможет настроить компилятор C++

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # Устанавливаем необходимые инструменты для компиляции

      - name: Build the project
        run: |
          g++ -o my_program game.cpp  # Пример компиляции, если у тебя один файл main.cpp, или подставь свой файл/проект

      - name: Run tests
        run: |
          ./my_program  # Запуск скомпилированной программы
