name: C++ CI Workflow

on:
  push:
  workflow_dispatch:
    branches:
      - main
    
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: linux ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: dependencies
      - run: 
          sudo apt update
          sudo apt install -y build-essential libgtest-dev

      - name: build
        run: |
          g++ -o game.cpp 

      - name: run
        run: |
         ./game  
